apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases: [../../base]
patches:
  - target: { kind: Deployment, name: cleus-api }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 4
  - target: { kind: Deployment, name: cleus-web }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
